config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  get 'books/index'
  get 'users/index',to: 'users#index'
  get 'rooms/index'
  #post 'reservation/create'
  devise_for :users
  resources :users
  root 'books#index'
  
  resources :rooms do  #ransack検索機能
  collection do
    get 'search',to: 'rooms#search'
  end   
  end 
  
  resources :reservations do
    collection do
      post :confirm
 end
 end
  
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/reservation.rb
class Reservation < ApplicationRecord 
  belongs_to :user
  belongs_to :room
  
  validates :checkin_day, presence: true
  validates :checkout_day, presence: true
  validates :num_people, presence: true
  validate :date_check
  validate :total_price

def date_check
 if checkout_day.present? && checkin_day.present? && checkin_day > checkout_day
  errors.add(:checkout_day,"は開始日より前の日を設定することはできません。")   
end
end

def days
  days = (checkout_day.to_date - checkin_day.to_date).to_i 
end

def total_price
 total_price = (days * num_people * room.room_price )
 end

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :resevations

  has_one_attached :image
  
  validates :room_name, presence: true
  validates :room_price, presence: true
  validates :room_address, presence: true
  validates :room_detail, presence: true
  
  
def self.ransackable_attributes(auth_object = nil)
    ["room_address"]
end
  #def self.ransackable_attributes(auth_object = nil)
    #%w[room_name room_address room_detail room_price]
  #end
  
  #def self.ransackable_associations(auth_object = nil)
        #[]
  #end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
             :recoverable, :rememberable, :validatable
             
  has_many :rooms
  has_many :resarvations
  has_one_attached :image
    
def self.ransackable_associations(auth_object = nil)
    ["room"] #アソシエーション先を記述
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action:configure_permitted_parameters, if: :devise_controller?

 def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
 end
 
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 
  before_action :set_q, only: [:index, :search]

  def index
  end

  def show
    @user = current_user
  end

  def search
    @results = @q.result
  end

  private

  def set_q
    @q = Room.ransack(params[:q])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user = current_user
    @reservations = Reservation.where(user_id: current_user.id )
  end

  def new
  @reservation = Reservation.new(reservation_params)
  end

  def create
     @room = Room.find_by(params[:reservation][:room_id])
     @user = User.find_by(params[:reservation][:room_id])
     @reservation = Reservation.new(reservation_params)
    if @reservation.save
      flash[:notice] = "予約を確定しました。"
      redirect_to :reservations
   else
      flash.now[:alert] = "予約に失敗しました"
      render "rooms/show"
  end
  end

  def show
  end

  def edit
  end

  def update

  end

  def destroy
   @reservation = Reservation.find(params[:id])
   @reservation.destroy
   flash[:notice] = "予約を削除しました"
   redirect_to :reservations
  end
  
  def confirm
    @room = Room.find(params[:reservation][:room_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.room_id = @room.id
     if @reservation.invalid?
      render template: "rooms/show"
      return
    end
  end
  
  
  def reservation_params
    params.require(:reservation).permit(:checkin_day, :checkout_day, :num_people,:total_price, :room_id, :user_id, :created_at)
  end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!, except: [:show,:new]#showアクションではログインを確認しない
  before_action :set_q, only: [:index, :search]
  #helper_method :current_user
 
  def index
   @rooms = current_user.rooms
  end
  
  def new
     @room = current_user.rooms.new
  end
 
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
     if @room.save
      flash[:notice] = "新規登録しました"
      redirect_to room_path(@room)
     else
       render :new
     end
   end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end
 
  def edit
    @room = Room.find(params[:id])
    if @room.user_id != current_user.id
      redirect_to room_path, alert: '編集権限がありません'
    end
  end
 
  def update
     @room = Room.find(params[:id])
     if @room.update(room_params)
       flash[:notice] = "ユーザーIDが「#{@room.user_id}」の情報を更新しました"
       redirect_to :rooms
     else
       render "edit"
     end
  end
 
  def destroy
  end
  
  def search
    @results = @q.result
  end

  private

  def room_params
    params.require(:room).permit(:room_name,:room_price,:room_address,:room_detail,:image)
  end
  
  def set_q
    @q = Room.ransack(params[:q])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
  @user = current_user
  end
  
def show
  @user = User.find(params[:id])
end
  
def edit
  @user = User.find(params[:id])
  if @user != current_user
   redirect_to users_path, alert: '不正なアクセスです'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "#{@user.id}の情報を更新しました"
      redirect_to user_path(@user)
    else
      render "edit"
    end
  end



 private
   def user_params
    params.require(:user).permit(:name, :introduction, :image)
   end

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<%= render "shared/partial" %>
<h1>Potepan Shareで</br>
まだ体験したことのない</br>
旅をしよう</h1>

<h3>住所検索</h3>
<%= search_form_for @q, url: search_rooms_path do |f| %>
  <%= f.label :room_address_cont, '住所' %>
  <%= f.search_field :room_address_cont %>
  <%= f.submit '検索' %>
<% end %>

<%= link_to '/rooms/search?q%5Broom_address_cont%5D=東京&commit=検索' do %>
<span>東京</span>
<% end %>

<%= link_to '/rooms/search?q%5Broom_address_cont%5D=大阪&commit=検索' do %>
<span>大阪</span>
<% end %>

<%= link_to '/rooms/search?q%5Broom_address_cont%5D=京都&commit=検索' do %>
<span>京都</span>
<% end %>
<%= link_to '/rooms/search?q%5Broom_address_cont%5D=札幌&commit=検索' do %>
<span>札幌</span>
<% end %>



<!-- _________________________________________________ -->

app/views/books/show.html.erb
<h1>設定</h1>

<%= link_to"アカウント" %>
<%= link_to"プロフィール", mypage_path %>
<h2>アカウント<h2>
<%= link_to"編集",edit_user_registration_path %>
<h3>メールアドレス</h3>
<%= @user.email %>
<h3>パスワード</h3>
<h4>********</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReserveApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/confirm.html.erb
<h2>予約情報の確認</h2>
<td>チェックイン</td>
<td><%= @reservation.checkin_day.strftime("%Y/%m/%d") %> </td>
<td>チェックアウト</td>
<td><%= @reservation.checkout_day.strftime("%Y/%m/%d") %>  </td>
<td>人数</td>     
<td><%= @reservation.num_people %> </td>
<td>合計金額</td>
<td><%= @reservation.total_price %> </td>

<%= form_with model: @reservation do  |f| %>
<%= f.hidden_field :user_id ,:value => @reservation.user.id %>
<%= f.hidden_field :room_id,:value => @reservation.room.id %>
<%= f.hidden_field :checkin_day,:value => @reservation.checkin_day %>
<%= f.hidden_field :checkout_day,:value => @reservation.checkout_day %>
<%= f.hidden_field :num_people,:value => @reservation.num_people %>
<%= f.hidden_field :total_price,:value => @reservation.total_price %>
        <%= f.submit "予約を確定" %>
<% end %>

app/views/reservations/index.html.erb
<%= render "shared/partial" %>
<p id="notice"><%= notice %></p>
<table>
<thead>
<tr>
<td>画像</td>
<td>施設名</td>
<td>紹介文</td>
<td>合計金額</td>
<td>チェックイン</td>
<td>チェックアウト</td>
<td>予約確定日時</td>
</tr>
</thead>

<tbody>
 <% if @reservations.count > 0 %>
 <% @reservations.each do |reservation| %>
      <tr>
        <td><%= image_tag reservation.room.image, class: 'reservation.room-image' if reservation.room.image.attached? %></td>
        <td><%= reservation.room.room_name %></td>
        <td><%= reservation.room.room_detail %></td>
        <td><%= reservation.total_price %></td>
        <td><%= reservation.checkin_day.strftime("%Y/%m/%d") %></td>
        <td><%= reservation.checkout_day.strftime("%Y/%m/%d") %></td>
        <td><%= reservation.created_at.strftime("%Y/%m/%d %H:%M") %></td>       
        <td><%= link_to "削除", reservation, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
         </td>
        </tr>
    <% end %>
    <% else %>
            <td colspan ="6">現在登録している施設はありません</td>
    <% end %>
</tbody>
    </table>

app/views/rooms/edit.html.erb
<%= render "shared/partial" %>
<p id="notice"><%= notice %></p>
<h3>施設登録の編集</h3>

<%= form_with model: @room do |f| %>
  <div class="field">
    <%= f.label :room_name, "施設名称"%>
    <%= f.text_field :room_name %>
  </div>

  <div class="field">
    <%= f.label :room_price, "金額"%>
    <%= f.number_field :room_price %>
  </div>
  
    <div class="field">
    <%= f.label :room_address, "住所"%>
    <%= f.text_field :room_address %>
  </div>

  <div class="field">
    <%= f.label :room_detail, "施設詳細情報"%>
    <%= f.text_field :room_detail %>
  </div>
  
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <ul>
    <li><%= f.submit "登録完了する" %></li>
    <li><%= link_to "ユーザー情報一覧に戻る", :rooms %></li>
  </ul>
<% end %>

app/views/rooms/index.html.erb
<%= render "shared/partial" %>
<p id="notice"><%= notice %></p>

<h1>ユーザーの登録施設一覧</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Address</th>
      <th>Detail</th>
      <th>Images</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
   <% if @rooms.count > 0 %>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.room_name %></td>
        <td><%= room.room_price %></td>
        <td><%= room.room_address %></td>
        <td><%= room.room_detail %></td>
        <td><% if room.image.attached? %>
        <%= image_tag room.image%>
         <% else %>
        <%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png' %>
        <% end %>
        </td>
        <td> <%= link_to "編集", [:edit, room] %>
         </td>
        </tr>
    <% end %>
    　<% else %>
        <td colspan ="6">現在登録している施設はありません</td>
        <% end %>
 
 
  </tbody>
</table>

app/views/rooms/new.html.erb
<%= render "shared/partial" %>
<p id="notice"><%= notice %></p>
<h3>検索登録</h3>

<%= form_with model: @room do |f| %>
  <div class="field">
    <%= f.label :room_name, "施設名称"%>
    <%= f.text_field :room_name %>
  </div>

  <div class="field">
    <%= f.label :room_price, "金額"%>
    <%= f.number_field :room_price %>
  </div>
  
    <div class="field">
    <%= f.label :room_address, "住所"%>
    <%= f.text_field :room_address %>
  </div>

  <div class="field">
    <%= f.label :room_detail, "施設詳細情報"%>
    <%= f.text_field :room_detail %>
  </div>
  
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <ul>
    <li><%= f.submit "登録完了する" %></li>
    <li><%= link_to "ユーザー情報一覧に戻る", :rooms %></li>
  </ul>
<% end %>

app/views/rooms/search.html.erb
<%= render "shared/partial" %>

<p id="notice"><%= notice %></p>

<h1> 検索一覧</h1>

<h3>検索画面</h3>
<%= search_form_for @q , url: search_rooms_path do |f| %>
  <%= f.search_field :room_address_cont %>
  <%= f.submit '検索' %>
<% end %>
  
<table>
  <thead>
    <tr>
      <th>施設名</th>
      <th>金額</th>
      <th>住所</th>
      <th>施設詳細</th>
      <th>施設画像</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @results.each do |room| %>
      <tr>
        <td><%= room.room_name %></td>
        <td><%= room.room_price %></td>
        <td><%= room.room_address %></td>
        <td><%= room.room_detail %></td>
        <td><%= image_tag room.image, class: 'room-image' if room.image.attached? %>
        <td><%= link_to "詳細", room %></td>
    <% end %></td>
      </tr>
    
 
  </tbody>
</table>


<%= link_to 'Top', root_path %>

app/views/rooms/show.html.erb
<%= render "shared/partial" %>
<h3>詳細画面</h3>
 
 <table>
   <tr>
     <th>施設名</th>
     <td><%= @room.room_name %></td>
   </tr>
   <tr>
     <th>住所</th>
     <td><%= @room.room_address %></td>
   </tr>
   <tr>
     <th>金額</th>
     <td><%= @room.room_price %></td>
   </tr>
   <tr>
     <th>施設紹介</th>
     <td><%= @room.room_detail %></td>
   </tr>
    <tr>
     <th>画像</th>
    <td><%= image_tag @room.image, class: 'room-image' if @room.image.attached? %></td>
 </table>
 
 <h3> 予約登録</h3>
<%= form_with model: @reservation ,url: confirm_reservations_path do |r| %>
      <%= r.hidden_field :room_id, :value => @room.id %>
      <%= r.hidden_field :user_id, :value => current_user&.id %>
      <%= r.hidden_field :room_price, :value => @room.room_price %>
  <div class="field">
    <%= r.label :checkin_day, "チェックイン"%>
    <%= r.date_field :checkin_day %>
  </div>
  <div class="field">
    <%= r.label :checkout_day, "チェックアウト"%>
    <%= r.date_field :checkout_day %>
  </div>
   <div class="field">
    <%= r.label :num_people, "人数"%>
    <%= r.number_field :num_people %>
  </div>
  <li><%= r.submit "予約する" %></li>
 <% end %>
<%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
 <div>
   <ul>
     <li><%= link_to "ユーザー情報一覧に戻る", :rooms %></li>
   </ul>
 </div>

  

app/views/shared/_partial.html.erb
 <header>
 <div class="site_header">
   <%=link_to"Potepan Share","/books/index",class:"site_title" %>

 <% if user_signed_in? %> 
  <!-- ユーザーがログインしていた時の処理 -->
    <div class="hamburger-menu">
        <input type="checkbox" id="menu-btn-check">
        <label for="menu-btn-check" class="menu-btn"><span></span></label>
              <div class="menu-content">
            <ul>        
    <% if current_user.image.attached? %>
    <%= image_tag current_user.image ,size:"50x50"%>
    <% else %>
    <%= image_tag 'https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png' %>
    <% end %>  
          <%= current_user.name %>
                <li>
                    <%=link_to "施設を新規登録する", :new_room %>
                </li>
                <li>
                      <%=link_to "予約済み一覧", :reservations_index %>
                </li>
                <li>
                      <%=link_to "登録済み一覧", :rooms_index %>
                </li>
                <li>
                      <%=link_to "アカウント設定", :users_index %>
                </li>
                <li>
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %> <!-- ログアウトをする -->
                </li>
            </ul>
        </div>
    </div>
    <% else %>
  <!-- ユーザーがログインしていなかった時の処理 -->
  <%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
  <%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
<% end %>
</div>
</header>

app/views/users/edit.html.erb
<%= render "shared/partial" %>
<p id="notice"><%= notice %></p>
<h2>プロフィール編集</h2>

<%= form_with model:@user do |f| %>
  
  <div class="field">
    <%= f.label :name, "ユーザー名" %><br />
    <%= f.text_field :name %>
  </div>
  
    <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>

  <div class="field">
    <%= f.label :introduction, "自己紹介" %><br />
    <%= f.text_area :introduction, :size=>"60x10" %>
  </div>
    
  <div class="actions">
    <%= f.submit "保存" %>
  </div>
<% end %>
<%= link_to "キャンセル", :back %>

app/views/users/index.html.erb
<%= render "shared/partial" %>
<p id="notice"><%= notice %></p>

<h1>設定</h1>

<%= link_to"アカウント" ,:users_index%>
<%= link_to"プロフィール", user_path(current_user)%>
<h2>アカウント<h2>
<%= link_to"編集",edit_user_registration_path %>
<h3>メールアドレス</h3>
<h4><%= @user.email %></h4>
<h3>パスワード</h3>
<h4>********</h4>

app/views/users/show.html.erb
<%= render "shared/partial" %>
<p id="notice"><%= notice %></p>

<h2>プロフィール</h2>


    <h3>アイコン画像</h3>
    <% if @user.image.attached? %>
    <%= image_tag @user.image %>
    <% else %>
    <%= image_tag 'https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png' %>
    <% end %>
       <h3>ユーザーネーム</h3>
       <h4><%= @user.name %></h4>
       <h3>自己紹介</h3>
       <h4><%= @user.introduction %></h4>
<%= link_to "編集", :edit_user %>
<%= link_to "キャンセル", :back %>